spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=a

spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create